#####basic########################
[[plugins]]
name = 'basic/dein.vim'
repo = 'Shougo/dein.vim'

[[plugins]]
name = 'basic/vimproc.vim'
repo = 'Shougo/vimproc.vim'

	[plugins.build]
	windows = 'tools\\update-dll-mingw'
	cygwin = 'make -f make_cygwin.mak'
	mac = 'make -f make_mac.mak'
	linux = 'make'
	unix = 'gmake'
##################################


#####git##########################
[[plugins]]
name = 'git/vim-unite-giti.git'
repo ='kmnk/vim-unite-giti.git'
##################################


#####memo#########################
[[plugins]]
name = 'memo/memolist.vim'
repo = 'glidenote/memolist.vim'
##################################


#####text##########################
[[plugins]]
name = 'text/molokai'
repo = 'tomasr/molokai'

[[plugins]]
name = "text/caw.vim"
repo = "tyru/caw.vim"

[[plugins]]
name = 'text/neosnippet'
repo = 'Shougo/neosnippet'

[[plugins]]
name = 'text/neosnippet-snippets'
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
name = 'name/deoplete.nvim'
repo = 'Shougo/deoplete.nvim'
on_i = 1
##################################

#####util#########################
[[plugins]]
name = 'util/wandbox-vim'
repo = 'rhysd/wandbox-vim'

[[plugins]]
name = 'util/vim-quickrun'
repo = 'thinca/vim-quickrun'

[[plugins]]
name = 'util/vim-scouter'
repo = 'thinca/vim-scouter'

[[plugins]]
name = 'util/TweetVim'
repo = 'basyura/TweetVim'

[[plugins]]
name = 'util/vim-tmux-navigator'
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
name = 'util/vim-over'
repo = 'osyo-manga/vim-over'

[[plugins]]
name = 'util/vimshell.vim'
repo = 'Shougo/vimshell.vim'

[[plugins]]
name = 'util/vinarise'
repo = 'Shougo/vinarise'
##################################


#####color########################
[[plugins]]
name = 'color/w3m.vim'
repo = 'yuratomo/w3m.vim'
##################################

#####ui###########################

[[plugins]]
repo   = 'Shougo/unite.vim'
lazy = 1

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']
lazy = 1

####################################

#####cpp############################
[[plugins]]
name = 'cpp/vim-clang'
repo = 'justmao945/vim-clang'
on_ft = ['cpp']
lazy = 1

[[plugins]]
name = 'cpp/vim-clang-format'
repo = 'rhysd/vim-clang-format'
on_ft = ['cpp']
lazy = 1

[[plugins]]
name = 'cpp/cpp-vim'
repo = 'vim-jp/cpp-vim'
on_ft = ['cpp']
lazy = 1
####################################

#####lisp###########################
[[plugins]]
name = 'lisp/slimv'
repo = 'kovisoft/slimv'
on_ft = ['lisp']
lazy = 1
####################################

#####haskell########################
[[plugins]]
name = 'haskell/vim2hs'
repo = 'dag/vim2hs'
on_ft = ['haskell']
lazy = 1

[[plugins]]
name = 'haskell/ghcmod-vim'
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']
lazy = 1

[[plugins]]
name = 'haskell/neco-ghc'
repo = 'eagletmt/neco-ghc'
on_ft = ['haskell']
lazy = 1

[[plugins]]
name = 'haskell/vim-filetype-haskell'
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']
lazy = 1
####################################
