#####text##########################
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
##################################
#####cpp############################
[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = 'cpp'
depend = ['Shougo/deoplete.nvim']

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = 'cpp'

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'
####################################

#####lisp###########################
[[plugins]]
repo = 'kovisoft/slimv'
on_ft = 'lisp'
####################################

#####haskell########################
[[plugins]]
repo = 'dag/vim2hs'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
depend = ['Shougo/deoplete.nvim']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = 'haskell'
####################################
