#####basic########################
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
##################################


#####git##########################
##################################

#####ui###########################
[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'kmnk/vim-unite-giti.git'

[[plugins]]
repo = 'miyakogi/seiya.vim'
####################################

#####util#########################
[[plugins]]
repo = 'rhysd/wandbox-vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'thinca/vim-scouter'

[[plugins]]
repo = 'basyura/TweetVim'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vinarise'

[[plugins]]
repo = 'glidenote/memolist.vim'
##################################

#####text##########################
[[plugins]]
repo = "sjl/badwolf"

[[plugins]]
repo = "tyru/caw.vim"

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'yuratomo/w3m.vim'
##################################
