#####text##########################
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
do = ':UpdateRemotePlugins'
##################################

#####ui############################
[[plugins]]
repo = 'shougo/denite.nvim'
on_cmd = 'denite'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_if = 1
on_event = 'TextYankPost'
on_source = ['denite.nvim']


[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTree'
##################################

[[plugins]]
repo = 'Shougo/deol.nvim'
on_cmd = 'Deol'

#####cpp############################
[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = 'cpp'

[[plugins]]
repo = 'rhysd/vim-clang-format'
on_ft = 'cpp'

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'

[[plugins]]
repo = 'vim-scripts/DoxygenToolkit.vim'
on_ft = 'cpp'

[[plugins]]
repo = 'osyo-manga/vim-stargate'
on_ft = 'cpp'
####################################

#####lisp###########################
[[plugins]]
repo = 'kovisoft/slimv'
on_ft = 'lisp'
####################################

#####haskell########################
####################################
#
#####rust###########################
[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'
####################################
#
#####python#########################
[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'
####################################
#
#####tex############################
[[plugins]]
repo='lervag/vim-latex'
on_ft = 'latex'
####################################
#
#####lint/lsp#######################
[[plugins]]
repo='w0rp/ale'
on_ft = ['python']

[[plugins]]
repo='autozimu/LanguageClient-neovim'
on_ft = ['haskell']
do = 'bash install.sh'
####################################
