#####basic########################
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'
##################################


#####git##########################
##################################

#####ui###########################
[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'cocopon/lightline-hybrid.vim'

[[plugins]]
repo = 'jlanzarotta/bufexplorer'
####################################

#####util#########################
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'haya14busa/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-speeddating'
##################################

#####text##########################
[[plugins]]
repo = "altercation/vim-colors-solarized"

[[plugins]]
repo = "tyru/caw.vim"

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
##################################
